version: '3.8'

services:
  ai-fitness-coach:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-fitness-coach
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_PATH=/app/data/fitness-coach.db
    env_file:
      - .env
    volumes:
      # Persist database
      - ./data:/app/data
      # Optional: mount tokens directory if using Google Calendar
      - ./tokens:/app/tokens
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-fitness-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: ai-fitness-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
      # For SSL certificates
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ai-fitness-coach
    networks:
      - ai-fitness-network

networks:
  ai-fitness-network:
    driver: bridge

volumes:
  data:
  tokens:
