const express = require('express');
const router = express.Router();
const fs = require('fs').promises;
const path = require('path');
const crypto = require('crypto');
const adminService = require('../services/adminService.cjs');
const apiKeyLoader = require('../services/apiKeyLoader.cjs');

// Middleware to verify admin token
const verifyAdminToken = (req, res, next) => {
  const token = req.headers.authorization?.replace('Bearer ', '');

  if (!token) {
    return res.status(401).json({ error: 'No token provided' });
  }

  try {
    const decoded = adminService.verifyToken(token);
    req.admin = decoded;
    next();
  } catch (error) {
    return res.status(401).json({ error: 'Invalid or expired token' });
  }
};

/**
 * Helper function to generate image with DALL-E 3 API
 */
async function generateImageWithKey(req, res, apiKey, prompt, aspectRatio) {
  try {
    // Use DALL-E 3 from OpenAI (more reliable and widely available)
    console.log('📡 Calling DALL-E 3 API...');
    
    // Map aspect ratio to DALL-E 3 size
    let size = '1024x1024'; // Default square
    if (aspectRatio === '16:9') size = '1792x1024';
    if (aspectRatio === '9:16') size = '1024x1792';
    
    const response = await fetch(
      'https://api.openai.com/v1/images/generations',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: 'dall-e-3',
          prompt: prompt,
          n: 1,
          size: size,
          quality: 'standard',
          response_format: 'b64_json'
        })
      }
    );

    console.log('📊 DALL-E 3 API response status:', response.status);

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('❌ DALL-E 3 API error:', errorData);
      return res.status(response.status).json({ 
        success: false, 
        error: errorData.error?.message || 'Failed to generate image' 
      });
    }

    const data = await response.json();
    console.log('✅ Image generated successfully with DALL-E 3');
    
    // DALL-E 3 response format: { data: [{ b64_json: "..." }] }
    if (!data.data || data.data.length === 0 || !data.data[0].b64_json) {
      console.error('❌ No images in response. Response:', JSON.stringify(data, null, 2));
      return res.status(500).json({ 
        success: false, 
        error: 'No image generated by DALL-E 3' 
      });
    }
    
    const base64Image = data.data[0].b64_json;

    // Save to temporary file
    const uploadsDir = path.join(__dirname, '../uploads/personas');
    await fs.mkdir(uploadsDir, { recursive: true });

    const filename = `ai-generated-${crypto.randomBytes(8).toString('hex')}.png`;
    const filepath = path.join(uploadsDir, filename);
    
    console.log('💾 Saving image to:', filepath);
    
    // Convert base64 to buffer and save
    const imageBuffer = Buffer.from(base64Image, 'base64');
    await fs.writeFile(filepath, imageBuffer);

    console.log('✅ Image saved successfully');

    res.json({
      success: true,
      imageUrl: `/uploads/personas/${filename}`,
      prompt: prompt
    });
  } catch (error) {
    console.error('❌ Error in generateImageWithKey:', error);
    console.error('Stack:', error.stack);
    throw error;
  }
}

/**
 * Generate image using Google Imagen 3
 * POST /api/image-generation/generate
 */
router.post('/generate', verifyAdminToken, async (req, res) => {
  try {
    const { prompt, aspectRatio = '1:1' } = req.body;
    console.log('🎨 Image generation request received');
    console.log('Prompt:', prompt);

    if (!prompt) {
      return res.status(400).json({ 
        success: false, 
        error: 'Prompt is required' 
      });
    }

    // Get OpenAI API key from apiKeyLoader service
    const apiKey = apiKeyLoader.getApiKey('openai');
    console.log('🔑 OpenAI API Key loaded:', apiKey ? 'Yes' : 'No');
    console.log('🔑 Available providers:', apiKeyLoader.getAvailableProviders());
    
    if (!apiKey) {
      console.error('❌ OpenAI API key not found in cache or .env');
      console.log('💡 Attempting to refresh API keys from database...');
      
      // Try refreshing keys from database
      await apiKeyLoader.refreshKeys();
      const refreshedKey = apiKeyLoader.getApiKey('openai');
      
      if (!refreshedKey) {
        console.error('❌ Still no OpenAI API key after refresh');
        return res.status(400).json({ 
          success: false, 
          error: 'OpenAI API key not configured. Please add it in Admin > API Keys and ensure it is marked as Active.' 
        });
      }
      
      console.log('✅ OpenAI API key loaded after refresh');
      // Use the refreshed key
      return await generateImageWithKey(req, res, refreshedKey, prompt, aspectRatio);
    }

    // Use the helper function to generate the image
    return await generateImageWithKey(req, res, apiKey, prompt, aspectRatio);

  } catch (error) {
    console.error('Error generating image:', error);
    console.error('Error stack:', error.stack);
    res.status(500).json({ 
      success: false, 
      error: error.message || 'Failed to generate image',
      details: process.env.NODE_ENV === 'development' ? error.stack : undefined
    });
  }
});

module.exports = router;
